#ifndef PROTOCOLDEFS_H
#define PROTOCOLDEFS_H

#include <QListWidgetItem>

/*! Defines for protocol editor draggable objects */
#define PROT_DRAG_LIST_WIDGET_ITEM_TYPE (QListWidgetItem::UserType)
#define PROT_DRAG_LIST_STIMULUS_ITEM_TYPE (PROT_DRAG_LIST_WIDGET_ITEM_TYPE+1)
#define PROT_DRAG_LIST_VSTEP_TSTEP_ITEM_TYPE (PROT_DRAG_LIST_STIMULUS_ITEM_TYPE+1)
#define PROT_DRAG_LIST_ISTEP_TSTEP_ITEM_TYPE (PROT_DRAG_LIST_VSTEP_TSTEP_ITEM_TYPE+1)
#define PROT_DRAG_LIST_VSTEP_ITEM_TYPE (PROT_DRAG_LIST_ISTEP_TSTEP_ITEM_TYPE+1)
#define PROT_DRAG_LIST_ISTEP_ITEM_TYPE (PROT_DRAG_LIST_VSTEP_ITEM_TYPE+1)
#define PROT_DRAG_LIST_VTSTEP_ITEM_TYPE (PROT_DRAG_LIST_ISTEP_ITEM_TYPE+1)
#define PROT_DRAG_LIST_ITSTEP_ITEM_TYPE (PROT_DRAG_LIST_VTSTEP_ITEM_TYPE+1)
#define PROT_DRAG_LIST_VCONST_ITEM_TYPE (PROT_DRAG_LIST_ITSTEP_ITEM_TYPE+1)
#define PROT_DRAG_LIST_ICONST_ITEM_TYPE (PROT_DRAG_LIST_VCONST_ITEM_TYPE+1)
#define PROT_DRAG_LIST_VHOLD_ITEM_TYPE (PROT_DRAG_LIST_ICONST_ITEM_TYPE+1)
#define PROT_DRAG_LIST_IHOLD_ITEM_TYPE (PROT_DRAG_LIST_VHOLD_ITEM_TYPE+1)
#define PROT_DRAG_LIST_VREST_ITEM_TYPE (PROT_DRAG_LIST_IHOLD_ITEM_TYPE+1)
#define PROT_DRAG_LIST_IREST_ITEM_TYPE (PROT_DRAG_LIST_VREST_ITEM_TYPE+1)
#define PROT_DRAG_LIST_VRAMP_ITEM_TYPE (PROT_DRAG_LIST_IREST_ITEM_TYPE+1)
#define PROT_DRAG_LIST_IRAMP_ITEM_TYPE (PROT_DRAG_LIST_VRAMP_ITEM_TYPE+1)
#define PROT_DRAG_LIST_VSIN_ITEM_TYPE (PROT_DRAG_LIST_IRAMP_ITEM_TYPE+1)
#define PROT_DRAG_LIST_ISIN_ITEM_TYPE (PROT_DRAG_LIST_VSIN_ITEM_TYPE+1)
#define PROT_DRAG_LIST_LOOPS_ITEM_TYPE (PROT_DRAG_LIST_ISIN_ITEM_TYPE+1)
#define PROT_DRAG_LIST_VREP_SEQ_SCALED_ITEM_TYPE (PROT_DRAG_LIST_LOOPS_ITEM_TYPE+1)
#define PROT_DRAG_LIST_IREP_SEQ_SCALED_ITEM_TYPE (PROT_DRAG_LIST_VREP_SEQ_SCALED_ITEM_TYPE+1)
#define PROT_DRAG_LIST_VREP_SEQ_ITEM_TYPE (PROT_DRAG_LIST_IREP_SEQ_SCALED_ITEM_TYPE+1)
#define PROT_DRAG_LIST_IREP_SEQ_ITEM_TYPE (PROT_DRAG_LIST_VREP_SEQ_ITEM_TYPE+1)
#define PROT_DRAG_LIST_VREP_SEQ_WITH_STEPS_ITEM_TYPE (PROT_DRAG_LIST_IREP_SEQ_ITEM_TYPE+1)
#define PROT_DRAG_LIST_IREP_SEQ_WITH_STEPS_ITEM_TYPE (PROT_DRAG_LIST_VREP_SEQ_WITH_STEPS_ITEM_TYPE+1)
#define PROT_DRAG_LIST_VINF_REP_SEQ_ITEM_TYPE (PROT_DRAG_LIST_IREP_SEQ_WITH_STEPS_ITEM_TYPE+1)
#define PROT_DRAG_LIST_IINF_REP_SEQ_ITEM_TYPE (PROT_DRAG_LIST_VINF_REP_SEQ_ITEM_TYPE+1)
#define PROT_DRAG_LIST_CONTROL_ITEM_TYPE (PROT_DRAG_LIST_IINF_REP_SEQ_ITEM_TYPE+1)
#define PROT_DRAG_LIST_VOLTAGE_CONTROL_ITEM_TYPE (PROT_DRAG_LIST_CONTROL_ITEM_TYPE+1)
#define PROT_DRAG_LIST_CURRENT_CONTROL_ITEM_TYPE (PROT_DRAG_LIST_VOLTAGE_CONTROL_ITEM_TYPE+1)
#define PROT_DRAG_LIST_TIME_CONTROL_ITEM_TYPE (PROT_DRAG_LIST_CURRENT_CONTROL_ITEM_TYPE+1)
#define PROT_DRAG_LIST_FREQUENCY_CONTROL_ITEM_TYPE (PROT_DRAG_LIST_TIME_CONTROL_ITEM_TYPE+1)
#define PROT_DRAG_LIST_NATURAL_NUM_CONTROL_ITEM_TYPE (PROT_DRAG_LIST_FREQUENCY_CONTROL_ITEM_TYPE+1)
#define PROT_DRAG_LIST_SEPARATOR_TYPE (PROT_DRAG_LIST_NATURAL_NUM_CONTROL_ITEM_TYPE+1)

#define PROT_DROP_LIST_WIDGET_ITEM_TYPE (QListWidgetItem::UserType+100)
#define PROT_DROP_LIST_STIMULUS_ITEM_TYPE (PROT_DROP_LIST_WIDGET_ITEM_TYPE+1)
#define PROT_DROP_LIST_VSTEP_TSTEP_ITEM_TYPE (PROT_DROP_LIST_STIMULUS_ITEM_TYPE+1)
#define PROT_DROP_LIST_ISTEP_TSTEP_ITEM_TYPE (PROT_DROP_LIST_VSTEP_TSTEP_ITEM_TYPE+1)
#define PROT_DROP_LIST_VSTEP_ITEM_TYPE (PROT_DROP_LIST_ISTEP_TSTEP_ITEM_TYPE+1)
#define PROT_DROP_LIST_ISTEP_ITEM_TYPE (PROT_DROP_LIST_VSTEP_ITEM_TYPE+1)
#define PROT_DROP_LIST_VTSTEP_ITEM_TYPE (PROT_DROP_LIST_ISTEP_ITEM_TYPE+1)
#define PROT_DROP_LIST_ITSTEP_ITEM_TYPE (PROT_DROP_LIST_VTSTEP_ITEM_TYPE+1)
#define PROT_DROP_LIST_VCONST_ITEM_TYPE (PROT_DROP_LIST_ITSTEP_ITEM_TYPE+1)
#define PROT_DROP_LIST_ICONST_ITEM_TYPE (PROT_DROP_LIST_VCONST_ITEM_TYPE+1)
#define PROT_DROP_LIST_VHOLD_ITEM_TYPE (PROT_DROP_LIST_ICONST_ITEM_TYPE+1)
#define PROT_DROP_LIST_IHOLD_ITEM_TYPE (PROT_DROP_LIST_VHOLD_ITEM_TYPE+1)
#define PROT_DROP_LIST_VREST_ITEM_TYPE (PROT_DROP_LIST_IHOLD_ITEM_TYPE+1)
#define PROT_DROP_LIST_IREST_ITEM_TYPE (PROT_DROP_LIST_VREST_ITEM_TYPE+1)
#define PROT_DROP_LIST_VRAMP_ITEM_TYPE (PROT_DROP_LIST_IREST_ITEM_TYPE+1)
#define PROT_DROP_LIST_IRAMP_ITEM_TYPE (PROT_DROP_LIST_VRAMP_ITEM_TYPE+1)
#define PROT_DROP_LIST_VSIN_ITEM_TYPE (PROT_DROP_LIST_IRAMP_ITEM_TYPE+1)
#define PROT_DROP_LIST_ISIN_ITEM_TYPE (PROT_DROP_LIST_VSIN_ITEM_TYPE+1)
#define PROT_DROP_LIST_LOOPS_ITEM_TYPE (PROT_DROP_LIST_ISIN_ITEM_TYPE+1)
#define PROT_DROP_LIST_VREP_SEQ_SCALED_ITEM_TYPE (PROT_DROP_LIST_LOOPS_ITEM_TYPE+1)
#define PROT_DROP_LIST_IREP_SEQ_SCALED_ITEM_TYPE (PROT_DROP_LIST_VREP_SEQ_SCALED_ITEM_TYPE+1)
#define PROT_DROP_LIST_VREP_SEQ_ITEM_TYPE (PROT_DROP_LIST_IREP_SEQ_SCALED_ITEM_TYPE+1)
#define PROT_DROP_LIST_IREP_SEQ_ITEM_TYPE (PROT_DROP_LIST_VREP_SEQ_ITEM_TYPE+1)
#define PROT_DROP_LIST_VREP_SEQ_WITH_STEPS_ITEM_TYPE (PROT_DROP_LIST_IREP_SEQ_ITEM_TYPE+1)
#define PROT_DROP_LIST_IREP_SEQ_WITH_STEPS_ITEM_TYPE (PROT_DROP_LIST_VREP_SEQ_WITH_STEPS_ITEM_TYPE+1)
#define PROT_DROP_LIST_VINF_REP_SEQ_ITEM_TYPE (PROT_DROP_LIST_IREP_SEQ_WITH_STEPS_ITEM_TYPE+1)
#define PROT_DROP_LIST_IINF_REP_SEQ_ITEM_TYPE (PROT_DROP_LIST_VINF_REP_SEQ_ITEM_TYPE+1)
#define PROT_DROP_LIST_CONTROL_ITEM_TYPE (PROT_DROP_LIST_IINF_REP_SEQ_ITEM_TYPE+1)
#define PROT_DROP_LIST_VOLTAGE_CONTROL_ITEM_TYPE (PROT_DROP_LIST_CONTROL_ITEM_TYPE+1)
#define PROT_DROP_LIST_CURRENT_CONTROL_ITEM_TYPE (PROT_DROP_LIST_VOLTAGE_CONTROL_ITEM_TYPE+1)
#define PROT_DROP_LIST_TIME_CONTROL_ITEM_TYPE (PROT_DROP_LIST_CURRENT_CONTROL_ITEM_TYPE+1)
#define PROT_DROP_LIST_FREQUENCY_CONTROL_ITEM_TYPE (PROT_DROP_LIST_TIME_CONTROL_ITEM_TYPE+1)
#define PROT_DROP_LIST_NATURAL_NUM_CONTROL_ITEM_TYPE (PROT_DROP_LIST_FREQUENCY_CONTROL_ITEM_TYPE+1)

#define PROT_DRAG_LIST_WIDGET_ITEM_MIME_FORMAT "class/prot-drag-list-widget-item"
#define PROT_DRAG_LIST_STIMULUS_ITEM_MIME_FORMAT "class/prot-drag-list-stimulus-item"
#define PROT_DRAG_LIST_VSTEP_TSTEP_ITEM_MIME_FORMAT "class/prot-drag-list-vstep-tstep-item"
#define PROT_DRAG_LIST_ISTEP_TSTEP_ITEM_MIME_FORMAT "class/prot-drag-list-istep-tstep-item"
#define PROT_DRAG_LIST_VSTEP_ITEM_MIME_FORMAT "class/prot-drag-list-vstep-item"
#define PROT_DRAG_LIST_ISTEP_ITEM_MIME_FORMAT "class/prot-drag-list-istep-item"
#define PROT_DRAG_LIST_VTSTEP_ITEM_MIME_FORMAT "class/prot-drag-list-vtstep-item"
#define PROT_DRAG_LIST_ITSTEP_ITEM_MIME_FORMAT "class/prot-drag-list-itstep-item"
#define PROT_DRAG_LIST_VCONST_ITEM_MIME_FORMAT "class/prot-drag-list-vconst-item"
#define PROT_DRAG_LIST_ICONST_ITEM_MIME_FORMAT "class/prot-drag-list-iconst-item"
#define PROT_DRAG_LIST_VHOLD_ITEM_MIME_FORMAT "class/prot-drag-list-vhold-item"
#define PROT_DRAG_LIST_IHOLD_ITEM_MIME_FORMAT "class/prot-drag-list-ihold-item"
#define PROT_DRAG_LIST_VREST_ITEM_MIME_FORMAT "class/prot-drag-list-vrest-item"
#define PROT_DRAG_LIST_IREST_ITEM_MIME_FORMAT "class/prot-drag-list-irest-item"
#define PROT_DRAG_LIST_VRAMP_ITEM_MIME_FORMAT "class/prot-drag-list-vramp-item"
#define PROT_DRAG_LIST_IRAMP_ITEM_MIME_FORMAT "class/prot-drag-list-iramp-item"
#define PROT_DRAG_LIST_VSIN_ITEM_MIME_FORMAT "class/prot-drag-list-vsin-item"
#define PROT_DRAG_LIST_ISIN_ITEM_MIME_FORMAT "class/prot-drag-list-isin-item"
#define PROT_DRAG_LIST_LOOPS_ITEM_MIME_FORMAT "class/prot-drag-list-loops-item"
#define PROT_DRAG_LIST_VREP_SEQ_SCALED_ITEM_MIME_FORMAT "class/prot-drag-list-irep-seq-scaled-item"
#define PROT_DRAG_LIST_IREP_SEQ_SCALED_ITEM_MIME_FORMAT "class/prot-drag-list-irep-seq-scaled-item"
#define PROT_DRAG_LIST_VREP_SEQ_ITEM_MIME_FORMAT "class/prot-drag-list-vrep-seq-item"
#define PROT_DRAG_LIST_IREP_SEQ_ITEM_MIME_FORMAT "class/prot-drag-list-irep-seq-item"
#define PROT_DRAG_LIST_VREP_SEQ_WITH_STEPS_ITEM_MIME_FORMAT "class/prot-drag-list-vrep-seq-with-steps-item"
#define PROT_DRAG_LIST_IREP_SEQ_WITH_STEPS_ITEM_MIME_FORMAT "class/prot-drag-list-irep-seq-with-steps-item"
#define PROT_DRAG_LIST_VINF_REP_SEQ_ITEM_MIME_FORMAT "class/prot-drag-list-vinf-rep-seq-item"
#define PROT_DRAG_LIST_IINF_REP_SEQ_ITEM_MIME_FORMAT "class/prot-drag-list-iinf-rep-seq-item"
#define PROT_DRAG_LIST_CONTROL_ITEM_MIME_FORMAT "class/prot-drag-list-control-item"
#define PROT_DRAG_LIST_VOLTAGE_CONTROL_ITEM_MIME_FORMAT "class/prot-drag-list-voltage-control-item"
#define PROT_DRAG_LIST_CURRENT_CONTROL_ITEM_MIME_FORMAT "class/prot-drag-list-current-control-item"
#define PROT_DRAG_LIST_TIME_CONTROL_ITEM_MIME_FORMAT "class/prot-drag-list-time-control-item"
#define PROT_DRAG_LIST_FREQUENCY_CONTROL_ITEM_MIME_FORMAT "class/prot-drag-list-time-control-item"
#define PROT_DRAG_LIST_NATURAL_NUM_CONTROL_ITEM_MIME_FORMAT "class/prot-drag-list-natural-num-control-item"
#define PROT_DRAG_LIST_SEPARATOR_MIME_FORMAT "class/prot-drag-list-separator"

#define PROT_DROP_LIST_WIDGET_ITEM_MIME_FORMAT "class/prot-drop-list-widget-item"

#define PROT_EDITOR_STIMULUS_SEPARATOR_COLOR QColor(0xEA, 0xBF, 0xFF)
#define PROT_EDITOR_STIMULUS_ITEM_COLOR QColor(0xF4, 0xDE, 0xFF)
#define PROT_EDITOR_LOOPS_SEPARATOR_COLOR QColor(0xBF, 0xFF, 0xBF)
#define PROT_EDITOR_LOOPS_ITEM_COLOR QColor(0xDE, 0xFF, 0xDE)
#define PROT_EDITOR_CONTROLS_SEPARATOR_COLOR QColor(0xFF, 0xE6, 0xBF)
#define PROT_EDITOR_CONTROLS_ITEM_COLOR QColor(0xFF, 0xF2, 0xDE)
#define PROT_EDITOR_ANALYSIS_SEPARATOR_COLOR QColor(0xFF, 0xFF, 0xBF)
#define PROT_EDITOR_ANALYSIS_ITEM_COLOR QColor(0xFF, 0xFF, 0xDE)

#define PROT_WIDGET_VALID_COLOR QColor(0xBF, 0xFF, 0xBF)
#define PROT_WIDGET_INVALID_COLOR QColor(0xFF, 0xBF, 0xBF)

#define YAML_DEFAULT_FOLDER QString(QDir::homePath() + "/" + GLB_SOFTWARE_NAME +"/Protocols/")
#define YAML_DEFAULT_FILE QString("default")
#define YAML_FILE_EXTENSION QString(".yaml")

#define YAML_DEFAULT_FULL_FILE (YAML_DEFAULT_FOLDER+YAML_DEFAULT_FILE+YAML_FILE_EXTENSION)

#define YAML_LAST_FOLDER YAML_DEFAULT_FOLDER
#define YAML_LAST_FILE QString("last")
#define YAML_LAST_FULL_FILE (YAML_LAST_FOLDER+YAML_LAST_FILE+YAML_FILE_EXTENSION)

#define YAML_ANALYSIS_FOLDER YAML_DEFAULT_FOLDER
#define YAML_ANALYSIS_FILE QString("analysis")
#define YAML_ANALYSIS_FULL_FILE (YAML_ANALYSIS_FOLDER+YAML_ANALYSIS_FILE+YAML_FILE_EXTENSION)

#define YAML_VHOLD0_FOLDER YAML_DEFAULT_FOLDER
#define YAML_VHOLD0_FILE QString("vhold0")
#define YAML_VHOLD0_FULL_FILE (YAML_VHOLD0_FOLDER+YAML_VHOLD0_FILE+YAML_FILE_EXTENSION)

#define YAML_IHOLD0_FOLDER YAML_DEFAULT_FOLDER
#define YAML_IHOLD0_FILE QString("ihold0")
#define YAML_IHOLD0_FULL_FILE (YAML_IHOLD0_FOLDER+YAML_IHOLD0_FILE+YAML_FILE_EXTENSION)

#define YAML_LAST_PROTOCOL_FOLDER YAML_DEFAULT_FOLDER
#define YAML_LAST_PROTOCOL_FILE QString("last protocol")
#define YAML_LAST_PROTOCOL_FULL_FILE (YAML_LAST_PROTOCOL_FOLDER+YAML_LAST_PROTOCOL_FILE+YAML_FILE_EXTENSION)

typedef enum {
    ProtocolTypeGapfree = 0,
    ProtocolTypeEpisodic = 1
} ProtocolType_t;

typedef enum {
    ProtocolConsumerNone, /*!< This is a marker, must not be used to identify single consumer types */
    ProtocolConsumerDataWriter,
    ProtocolConsumerTypesNum /*!< This is a marker, must not be used to identify single consumer types */
} ProtocolConsumerType_t;

typedef enum {
    ProtocolApplicationSuccess,
    ErrorNotEnoughItemsForSequence,
    ErrorOverlappingSequences,
    ErrorMidInfiniteSequence,
    ErrorItemsOverflow,
    ErrorItemsNotFound,
    ErrorItemsOverStimulus,
    ErrorItemsUnderStimulus,
    ErrorItemsUnderDuration,
    ErrorItemsNotProcessed,
    ErrorProtocolInhibited,
    ProtocolApplicationStatusNum
} ProtocolApplicationStatus_t;

#define PTD_PROTOCOL_ANALYSIS_OFFSET (ProtocolConsumerAnalysis+1)
#define PTD_PROTOCOL_ANALYSIS_NUM (ProtocolConsumerTypesNum-PTD_PROTOCOL_ANALYSIS_OFFSET)

#endif // PROTOCOLDEFS_H
